### ISSUE TITLE
DC Motors PID

### ISSUE THREAD

**Issue by mohamedmostafaa** [LamaNIkesh/arduinoWallFollower#1]
Can you help me to use DC Motors Instead of Servos
thanks in advance

**Comment by LamaNIkesh** [comment]
Servo motors work with angles whereas dc motors can be easily modulated with PWM(Pulse width modulation). So values from 0-255 will change the speed of a dc motor. I think applying it into dc motor should be even simpler than using servos. The PID calculation should return values that corresponds to the DC speed. That's the only change you would need. 

This might be helpful, https://www.allaboutcircuits.com/projects/control-a-motor-with-an-arduino/

**Comment by mohamedmostafaa** [comment]
You are right for sure but i'm suffering of the right direction Speed it's come close to the wall and brok my first IR Sensor please give me a little help

**Comment by mohamedmostafaa** [comment]
i wanna to move it smoothly like your robot i spend 5 days trying to do that but always fail

**Comment by mohamedmostafaa** [comment]
#include <Servo.h>

#define  TRIGPIN  11
#define  ECHOPIN  12
#define left_irPin A0
#define right_irPin A1

//L298N control pins
const int LeftMotorForward = 2;
const int LeftMotorBackward = 4;
const int RightMotorForward = 7;
const int RightMotorBackward = 8;
 
int SonarDistance;           
int IrDistance;

int leftIrDistance;
int rightIrDistance;

int left_setpoint = 400; 
int right_setpoint = 380;
int threshold =15;
float error = 0;
//PID parameters
float integral = 0;
float derivative = 0;
float last_error = 0;
float PID_value = 0;
//tuning these parameters is pain in the ass.
//probably could use some optimisation to reach best option but too much work
float Kp = 3.0;
float Ki = 0.005;
float Kd = 1.3;
//These correction speed are purely experimental
//Needs to manually checked to get the appropriate correction speed
int correctionSpeed=54;         
int correctionSpeedR = 45;
int rightWheelSpeed;
int rightWheelPWM = 6;
int leftWheelSpeed;
int leftWheelPWM = 3;
int base_speedLeft=30;
int base_speedRight =150;

Servo servo_motor; 


void setup()
{
  Serial.begin(9600);
  pinMode(ECHOPIN, INPUT);
  pinMode(TRIGPIN, OUTPUT);
  
  pinMode(RightMotorForward, OUTPUT);
  pinMode(LeftMotorForward, OUTPUT);
  pinMode(LeftMotorBackward, OUTPUT);
  pinMode(RightMotorBackward, OUTPUT);
  pinMode(rightWheelPWM, OUTPUT);
  pinMode(leftWheelPWM, OUTPUT);
  
// ultra Servo
  servo_motor.attach(10); 
  servo_motor.write(90);
  
 }

void loop()
{
      reading_sensors(right_irPin); 
      pid_calculation(right_setpoint);
      rightwall_follow();
}

//-----------------------------------------Functions------------------------------------

//allows to choose whether to read left or right ir sensor
void reading_sensors(int choose_ir_sensor)
{
  int sensor_pin = choose_ir_sensor;             //sensor pin could be left or right IR pin
  digitalWrite(TRIGPIN, LOW);                   // Set the trigger pin to low for 2uS
  delayMicroseconds(2);
  digitalWrite(TRIGPIN, HIGH);                  // Send a 10uS high to trigger ranging
  delayMicroseconds(10);
  digitalWrite(TRIGPIN, LOW);                   // Send pin low again
  int distance = pulseIn(ECHOPIN, HIGH);        // Read in times pulse

  SonarDistance = distance/58;// Calculate distance from time of pulse
//  Serial.print("Sonar Sensor: ");
//  Serial.println(SonarDistance);                     
  delay(50); 
  
  IrDistance= analogRead(sensor_pin);             //read the sensor
//  Serial.print(" IR sensor reading: ") ;
//  Serial.print(IrDistance);
//  Serial.println("cm");
  delay(50);
  
}
//===========================================================================================================================================
void pid_calculation(int choose_setpoint)          // does the pid calculation, setpoint can be changed either for left or right sensor   //=
{                                                                                                                                         //=
  //taking the difference in reading 
  int setpoint = choose_setpoint;
  //IrDistance could be left or right depending on the wall follwing algorithm..
  error= IrDistance - setpoint;
//  Serial.print("IrDistance");
//  Serial.println(IrDistance);
//  Serial.print("error");
//  Serial.println(error);
//  delay(1000);
  //calculating integral 
  if(abs(error) < threshold)
  {
    integral = integral + error;
  }
  else
  {
    integral=0;
  }
  //taking the change in difference in reading
  derivative = error - last_error;
  last_error = error;
  //calulating PID value which is also an error value
  PID_value = int(error*Kp + integral*Ki + derivative*Kd);
  //return PID_value;
//  Serial.println("PID_value");
//  Serial.println(PID_value);
//  delay(1000);
}
//============================================================================================================================================

////----------------------------leftwallfollow--------------------------------------------------
//void leftwall_follow(){
//
//  //sets the PID_value to be lowest to -45 and highest to 45
//  if(PID_value< -correctionSpeed){
//    PID_value = -correctionSpeed;
//    //Serial.println(PID_value);
//    //delay(1000);
//  }
//  if(PID_value> correctionSpeed){
//    PID_value = correctionSpeed;
//    //Serial.println(PID_value);
//    // delay(1000);
//  }
//
//  if(PID_value < 0)
//  {
//    //away from the wall
//    rightWheelSpeed = base_speedRight - PID_value   ;
//    leftWheelSpeed = base_speedLeft - PID_value;
//  }
//  else
//  {
//    //right turn
//    rightWheelSpeed = base_speedRight - PID_value;
//    leftWheelSpeed = base_speedLeft - PID_value;
//  }
//
//  servoLeft.write(leftWheelSpeed);
//  servoRight.write(rightWheelSpeed);
// 
//
//
//  //sharp right turn(90 degree turn) when theres a wall on the left and wall at the front as well
//
//  if(SonarDistance <7 && SonarDistance!=0  && IrDistance > 100)
//  {
//    sharp_right();
//  }
//}
//
//void sharp_right()
//{
//
//  servoLeft.write(0);
//  servoRight.write(0);
// 
//  delay(430);
//  
//}

//----------------------------rightwallfollow--------------------------------------------------
void rightwall_follow(){
   Serial.println("rightwall_follow");
   if(PID_value< -correctionSpeedR){
    PID_value = -correctionSpeedR;
   //PID_value = map(PID_value , 0 , -255, 0, 255);
    Serial.println("PID_valueIF_<");
    Serial.println(PID_value);
    delay(1000);
  }
  if(PID_value> correctionSpeedR){
    PID_value = correctionSpeedR;
    Serial.println("PID_valueIF_>");
    Serial.println(PID_value);
     delay(1000);
  }

  if(PID_value < 0)
  {
    //away from the wall
      leftWheelSpeed = base_speedLeft + PID_value;
    rightWheelSpeed = base_speedRight + PID_value;
    Serial.println("away from the wall");
     Serial.println("leftWheelSpeed");
    Serial.println(leftWheelSpeed);
     delay(1000);
     Serial.println("rightWheelSpeed");
    Serial.println(rightWheelSpeed);
     delay(1000);
    
  }
  else
  {
    //left turn
    leftWheelSpeed = base_speedLeft + PID_value;
    rightWheelSpeed = base_speedRight + PID_value;
    Serial.println("left turn");
      Serial.println("leftWheelSpeed");
    Serial.println(leftWheelSpeed);
     delay(1000);
     Serial.println("rightWheelSpeed");
    Serial.println(rightWheelSpeed);
     delay(1000);
  }
     analogWrite(leftWheelPWM , leftWheelSpeed);
     analogWrite(rightWheelPWM , rightWheelSpeed);
    digitalWrite(LeftMotorForward, HIGH);
    digitalWrite(RightMotorForward, HIGH);
    digitalWrite(LeftMotorBackward, LOW);
    digitalWrite(RightMotorBackward, LOW);




  
  //sharp right turn when theres a wall on the left and wall at the front as well

//  if(SonarDistance <8 && SonarDistance!=0  && IrDistance > 150)
//  {
//    sharp_left();
//  }
}

void sharp_left()
{
  analogWrite(leftWheelPWM, 100);
  analogWrite(rightWheelPWM , 100);
    delay(600);
}

**Comment by mohamedmostafaa** [comment]
Serial reading
Far From Wall
rightwall_follow
PID_valueIF_>
45.00
left turn
leftWheelSpeed
75
rightWheelSpeed
195

Near to Wall
rightwall_follow
PID_valueIF_<
-45.00
away from the wall
leftWheelSpeed
-15
rightWheelSpeed
105

**Comment by mohamedmostafaa** [comment]
Dear My Friend 
thanks 
thanks alot
it's ok now
