### ISSUE TITLE
want to contact with you

### ISSUE THREAD

**Issue by mohamedmostafaa** [LamaNIkesh/arduinoWallFollower#2]
i need some help here if it possible 
i replaced the ir sensor with ultra sonic but something wrong
Edges problem happen how can i pass it?

**Comment by LamaNIkesh** [comment]
You can replace ir sensor with ultrasonic and viceversa but you will need to make adjustments accordingly. The values outputted by ir and ultrasonic sensors are different so you will need to print the sensor readings onto the monitor and make adjustments
